/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.funnybot.main;

import com.funnybot.filecontrollers.FileController;
import com.funnybot.helpers.DataLogController;
import com.funnybot.twittercontrollers.TwitterController;
import javax.swing.JFileChooser;


public class FunnyBotGUI extends javax.swing.JFrame implements Runnable{

    private long _threadSleepTimer = 5000;
    
    /**
     * Creates new form FunnyBotGUI
     */
    public FunnyBotGUI() {
        initComponents();
        
        FileController.Initialize(); // Initializing the file 
                                     // controller
                                     
        TwitterController.Initialize(); // Initializing the
                                        // twitter controller
                                        
        DataLogController.GetInstance() // Initializing the
                .SetDebugEnabled(true); // data log controller
    }

    @Override
    public void run() {
        while(true) // Continuous thread
        {
            try
            {
                Thread.sleep(_threadSleepTimer); // Thread sleeping
                
                // Updating the bottom bar
                LblCounter.setText(
                        "Success: " + 
                        DataLogController.GetInstance().GetSuccessCounter() + 
                        " Fail: " + 
                        DataLogController.GetInstance().GetFailCounter());
            }
            catch(InterruptedException e)
            {
                DataLogController.GetInstance()
                        .LogFailed("FunnyBotGUI, "
                                 + "run(), "
                                 + "InterruptedException, "
                                 + "Message: " + e.getMessage());
            }
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FileChooser = new javax.swing.JFileChooser();
        BtnTest = new javax.swing.JButton();
        TxtTest = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        LblCounter = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        MenuOpen = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        MenuCredentials = new javax.swing.JMenuItem();
        MenuLogPath = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BtnTest.setText("TestButton");
        BtnTest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnTestActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        LblCounter.setFont(new java.awt.Font("Dialog", 2, 12)); // NOI18N
        LblCounter.setForeground(new java.awt.Color(0, 0, 0));
        LblCounter.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        LblCounter.setText("Success: 0 Fail: 0");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LblCounter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LblCounter, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
        );

        jMenu1.setText("File");

        MenuOpen.setText("Open");
        MenuOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuOpenActionPerformed(evt);
            }
        });
        jMenu1.add(MenuOpen);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");

        MenuCredentials.setText("Credentials");
        MenuCredentials.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuCredentialsActionPerformed(evt);
            }
        });
        jMenu2.add(MenuCredentials);

        MenuLogPath.setText("Log Path");
        MenuLogPath.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuLogPathActionPerformed(evt);
            }
        });
        jMenu2.add(MenuLogPath);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(164, 164, 164)
                        .addComponent(TxtTest, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(264, 264, 264)
                        .addComponent(BtnTest)))
                .addContainerGap(175, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(115, Short.MAX_VALUE)
                .addComponent(TxtTest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BtnTest)
                .addGap(152, 152, 152)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MenuOpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuOpenActionPerformed
        // Setting the mode of the file chooser to files only
        FileChooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
        
        int status = FileChooser.showOpenDialog(this); // Getting status of
                                                       // the file chooser
                                                       
        // Condition to check if file chooser selected a file
        if(status == JFileChooser.APPROVE_OPTION)
        {
            FileController.GetInstance().LoadData(FileChooser.getSelectedFile()
                .toPath().toString());

            // Checking if data has been loaded
            if(FileController.GetInstance().IsDataTemp()){
                
                // Setting up twitter credentials
                TwitterController.GetInstance().SetCredentials(
                        FileController.GetInstance().GetData(0), 
                        FileController.GetInstance().GetData(1), 
                        FileController.GetInstance().GetData(2),
                        FileController.GetInstance().GetData(3));
                
                // Initializing twitter with new credentials
                TwitterController.GetInstance().SetupTwitter();
            }
        }
    }//GEN-LAST:event_MenuOpenActionPerformed

    private void MenuCredentialsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuCredentialsActionPerformed
        new CredentialUI().setVisible(true);
    }//GEN-LAST:event_MenuCredentialsActionPerformed

    private void BtnTestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnTestActionPerformed
        TwitterController.GetInstance().SendTweet(TxtTest.getText());
    }//GEN-LAST:event_BtnTestActionPerformed

    private void MenuLogPathActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuLogPathActionPerformed
        // Setting the mode of the file chooser to directories only
        FileChooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        
        int status = FileChooser.showOpenDialog(this); // Getting status of
                                                       // the file chooser

        // Condition to check if file chooser selected a file
        if(status == JFileChooser.APPROVE_OPTION)
        {
            // Setting the path of the data logger
            DataLogController.GetInstance().SetPath(
                    FileChooser.getSelectedFile()
                    .toPath().toString());
        }
    }//GEN-LAST:event_MenuLogPathActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FunnyBotGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FunnyBotGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FunnyBotGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FunnyBotGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FunnyBotGUI app = new FunnyBotGUI();
                app.setVisible(true);
                
                Thread appThread = new Thread(app);
                appThread.start();
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnTest;
    private javax.swing.JFileChooser FileChooser;
    private javax.swing.JLabel LblCounter;
    private javax.swing.JMenuItem MenuCredentials;
    private javax.swing.JMenuItem MenuLogPath;
    private javax.swing.JMenuItem MenuOpen;
    private javax.swing.JTextField TxtTest;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

}
