/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.funnybot.main;

import com.funnybot.filecontrollers.FileController;
import com.funnybot.helpers.DataLogController;
import com.funnybot.twittercontrollers.TimerCycleController;
import com.funnybot.twittercontrollers.TwitterController;
import javax.swing.JFileChooser;


public class FunnyBotGUI extends javax.swing.JFrame implements Runnable{

    private boolean _isStart;
    private Thread _appThread;
    
    /**
     * Creates new form FunnyBotGUI
     */
    public FunnyBotGUI() {
        initComponents();
        
        _isStart = false;
        
        FileController.Initialize(); // Initializing the file 
                                     // controller
                                     
        TwitterController.Initialize(); // Initializing the
                                        // twitter controller
                                        
        DataLogController.GetInstance() // Initializing the
                .SetDebugEnabled(true); // data log controller
        
        TimerCycleController.Initialize(); // Initializing the
                                           // timer cycle
                                           // controller
                                           
        _appThread = new Thread(this);
        _appThread.start();
    }

    /**
     * This method returns the status of the bot.
     * 
     * @return The status of the bot, of type String
     */
    private String GetBotStatus()
    {
        return _isStart ? "Status: On" : "Status: Off";
    }
    
    /**
     * This method updates the bottom bar.
     */
    private void UpdateBottomBar()
    {
        // Updating the bottom bar
        LblCounter.setText(
                GetBotStatus() + " - " +
                TimerCycleController.GetInstance().toString() 
                + " - " +
                "Success: " + 
                DataLogController.GetInstance()
                        .GetSuccessCounter() + 
                " Fail: " + 
                DataLogController.GetInstance()
                        .GetFailCounter());
    }
    
    @Override
    public void run() {
        while(true) // Continuous thread
        {
            // Condition for starting the bot
            if(_isStart)
            {
                try
                {
                    Thread.sleep(TimerCycleController
                            .GetInstance()
                            .GetTimer()); // Thread sleeping

                    // Condition for sending messages
                    if(DataLogController.GetInstance().IsSamdDay())
                    {
                        //Todo: Send tweet here
                    }
                    else // Condition for resetting the messages
                    {
                        DataLogController.GetInstance()
                                .SetCurrentDate();
                        
                        //Todo: Reset all the messages here
                    }
                    
                    System.out.println("Sent tweet!");
                    
                    // Updating the bottom bar
                    UpdateBottomBar();
                }
                catch(InterruptedException e)
                {
                    DataLogController.GetInstance()
                            .LogFailed("FunnyBotGUI, "
                                     + "run(), "
                                     + "InterruptedException, "
                                     + "Message: " + e.getMessage());
                }
            }
            else
            {
                // Updating the bottom bar
                UpdateBottomBar();
            }
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FileChooser = new javax.swing.JFileChooser();
        BtnTest = new javax.swing.JButton();
        TxtTest = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        LblCounter = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        MenuOpen = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        MenuCredentials = new javax.swing.JMenuItem();
        MenuLogPath = new javax.swing.JMenuItem();
        btnMenuSetTimer = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        btnStart = new javax.swing.JMenuItem();
        btnStop = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BtnTest.setText("TestButton");
        BtnTest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnTestActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        LblCounter.setFont(new java.awt.Font("Dialog", 2, 12)); // NOI18N
        LblCounter.setForeground(new java.awt.Color(0, 0, 0));
        LblCounter.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        LblCounter.setText("Status: Off - Success: 0 Fail: 0");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LblCounter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LblCounter, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
        );

        jMenu1.setText("File");

        MenuOpen.setText("Open");
        MenuOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuOpenActionPerformed(evt);
            }
        });
        jMenu1.add(MenuOpen);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");

        MenuCredentials.setText("Credentials");
        MenuCredentials.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuCredentialsActionPerformed(evt);
            }
        });
        jMenu2.add(MenuCredentials);

        MenuLogPath.setText("Log Path");
        MenuLogPath.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuLogPathActionPerformed(evt);
            }
        });
        jMenu2.add(MenuLogPath);

        btnMenuSetTimer.setText("Set Timer");
        btnMenuSetTimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuSetTimerActionPerformed(evt);
            }
        });
        jMenu2.add(btnMenuSetTimer);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Bot");

        btnStart.setText("Start");
        btnStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartActionPerformed(evt);
            }
        });
        jMenu3.add(btnStart);

        btnStop.setText("Stop");
        btnStop.setEnabled(false);
        btnStop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStopActionPerformed(evt);
            }
        });
        jMenu3.add(btnStop);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(164, 164, 164)
                        .addComponent(TxtTest, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(264, 264, 264)
                        .addComponent(BtnTest)))
                .addContainerGap(175, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(115, Short.MAX_VALUE)
                .addComponent(TxtTest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BtnTest)
                .addGap(152, 152, 152)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MenuOpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuOpenActionPerformed
        // Setting the mode of the file chooser to files only
        FileChooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
        
        int status = FileChooser.showOpenDialog(this); // Getting status of
                                                       // the file chooser
                                                       
        // Condition to check if file chooser selected a file
        if(status == JFileChooser.APPROVE_OPTION)
        {
            FileController.GetInstance().LoadData(FileChooser.getSelectedFile()
                .toPath().toString());

            // Checking if data has been loaded
            if(FileController.GetInstance().IsDataTemp()){
                
                // Setting up twitter credentials
                TwitterController.GetInstance().SetCredentials(
                        FileController.GetInstance().GetData(0), 
                        FileController.GetInstance().GetData(1), 
                        FileController.GetInstance().GetData(2),
                        FileController.GetInstance().GetData(3));
                
                // Initializing twitter with new credentials
                TwitterController.GetInstance().SetupTwitter();
            }
        }
    }//GEN-LAST:event_MenuOpenActionPerformed

    private void MenuCredentialsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuCredentialsActionPerformed
        new CredentialUI().setVisible(true);
    }//GEN-LAST:event_MenuCredentialsActionPerformed

    private void BtnTestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnTestActionPerformed
        TwitterController.GetInstance().SendTweet(TxtTest.getText());
    }//GEN-LAST:event_BtnTestActionPerformed

    private void MenuLogPathActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuLogPathActionPerformed
        // Setting the mode of the file chooser to directories only
        FileChooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        
        int status = FileChooser.showOpenDialog(this); // Getting status of
                                                       // the file chooser

        // Condition to check if file chooser selected a file
        if(status == JFileChooser.APPROVE_OPTION)
        {
            // Setting the path of the data logger
            DataLogController.GetInstance().SetPath(
                    FileChooser.getSelectedFile()
                    .toPath().toString());
        }
    }//GEN-LAST:event_MenuLogPathActionPerformed

    private void btnMenuSetTimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuSetTimerActionPerformed
        new TimerUI().setVisible(true);
    }//GEN-LAST:event_btnMenuSetTimerActionPerformed

    private void btnStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartActionPerformed
        _isStart = true; // Starting the bot
        btnStart.setEnabled(false);
        btnStop.setEnabled(true);
        
        DataLogController.GetInstance()
                .LogSuccess("Success: FunnyBotGUI, "
                        + "btnStartActionPerformed(ActionEvent), "
                        + "Successfully started the bot.");
        
        // Updating the bottom bar
        UpdateBottomBar();
        
        // Setting the current date
        DataLogController.GetInstance().SetCurrentDate();
    }//GEN-LAST:event_btnStartActionPerformed

    private void btnStopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStopActionPerformed
        _isStart = false; // Stopping the bot
        btnStart.setEnabled(true);
        btnStop.setEnabled(false);
        
        // Condition for stopping the thread
        if(!_appThread.isInterrupted()) _appThread.interrupt();
        
        DataLogController.GetInstance()
                .LogSuccess("Success: FunnyBotGUI, "
                        + "btnStopActionPerformed(ActionEvent), "
                        + "Successfully stopped the bot.");
    }//GEN-LAST:event_btnStopActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FunnyBotGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FunnyBotGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FunnyBotGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FunnyBotGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FunnyBotGUI app = new FunnyBotGUI();
                app.setVisible(true);
                
                /*Thread appThread = new Thread(app);
                appThread.start();*/
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnTest;
    private javax.swing.JFileChooser FileChooser;
    private javax.swing.JLabel LblCounter;
    private javax.swing.JMenuItem MenuCredentials;
    private javax.swing.JMenuItem MenuLogPath;
    private javax.swing.JMenuItem MenuOpen;
    private javax.swing.JTextField TxtTest;
    private javax.swing.JMenuItem btnMenuSetTimer;
    private javax.swing.JMenuItem btnStart;
    private javax.swing.JMenuItem btnStop;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

}
