/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.funnybot.main;

import com.funnybot.filecontrollers.FileController;
import com.funnybot.twittercontrollers.TwitterMessageController;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Kamran
 */
public class MessagesUI extends javax.swing.JFrame {

    private int _counter = 0;
    
    /**
     * Creates new form MessagesUI
     */
    public MessagesUI() {
        initComponents();
        
        // Centering the texts in the table
        DefaultTableCellRenderer centerRenderer = 
                new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment( JLabel.CENTER );
        TableTweets.setDefaultRenderer(String.class, centerRenderer);
        TableTweets.setDefaultRenderer(Integer.class, centerRenderer);
        
        // Setting the start message
        txtStartTweet.setText(TwitterMessageController
                .GetInstance().GetStartMessage());
            
        // Setting the end message
        txtEndTweet.setText(TwitterMessageController
                .GetInstance().GetEndMessage());
        
        LoadMessagesToTable();
    }

    /**
     * This method checks if the start,end and at least 1
     * tweet given.
     * 
     * @return True means all the necessary tweets are given,
     *         false otherwise, of type boolean
     */
    private boolean ValidateInfo()
    {
        // Condition to check if the validation failed
        if(txtStartTweet.getText().isEmpty() ||
           txtEndTweet.getText().isEmpty() ||
           !TwitterMessageController.GetInstance()
                   .HasTweetMessage())
        {
            return false; // Validation failed
        }
        
        return true; // Validation succeeded
    }
    
    /**
     * This method loads all the tweet messages into the table.
     */
    private void LoadMessagesToTable()
    {
        _counter = 0; // Resetting the counter
        
        // Loop to remove any row data if present
        while(GetTable().getRowCount() != 0)
        {
            // Removing row data
            GetTable().removeRow(0);
        }
        
        // Getting the message list
        List<String> data = TwitterMessageController.GetInstance()
                .GetData(false);

        // Loop for adding all the tweet messages
        // to the table
        for(int i = 0; i < data.size(); i++)
        {
            // Checking if message isn't end of file
            if(!data.get(i)
                    .equalsIgnoreCase(FileController.CommandDone)){
                // Adding the tweet message
                GetTable().addRow(new Object[]{_counter, data.get(i)});
                _counter++;
            }
        }
    }
    
    /**
     * This method returns the row addable table.
     * 
     * @return The addable table, of type DefaultTableModel
     */
    private DefaultTableModel GetTable(){
        return (DefaultTableModel)TableTweets.getModel();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FileChooser = new javax.swing.JFileChooser();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TextAreaTweet = new javax.swing.JTextArea();
        btnAddTweet = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        TableTweets = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        txtStartTweet = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtEndTweet = new javax.swing.JTextField();
        btnSet = new javax.swing.JButton();

        FileChooser.setSelectedFile(new java.io.File("C:\\Program Files\\NetBeans 8.2\\.txt"));

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Tweets");

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setText("Enter Tweet");

        TextAreaTweet.setColumns(20);
        TextAreaTweet.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        TextAreaTweet.setRows(5);
        jScrollPane1.setViewportView(TextAreaTweet);

        btnAddTweet.setText("Add Tweet");
        btnAddTweet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddTweetActionPerformed(evt);
            }
        });

        TableTweets.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Message"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(TableTweets);

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setText("Start Tweet");

        txtStartTweet.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel3.setText("End Tweet");

        txtEndTweet.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        btnSet.setText("Set");
        btnSet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnAddTweet)
                .addGap(306, 306, 306))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(281, 281, 281)
                                .addComponent(btnSet, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane2)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtEndTweet)
                                    .addComponent(txtStartTweet)))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 667, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(296, 296, 296)
                        .addComponent(jLabel1)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtStartTweet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtEndTweet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAddTweet)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnSet)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddTweetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddTweetActionPerformed
        TwitterMessageController.GetInstance()
                .AddMessage(TextAreaTweet.getText());
        
        // Adding the tweet message
        GetTable().addRow(new Object[]{_counter, TextAreaTweet.getText()});
        _counter++;
        TextAreaTweet.setText(""); // Removing all texts once added
    }//GEN-LAST:event_btnAddTweetActionPerformed

    private void btnSetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSetActionPerformed
        // Checking if the tweets given are valid
        if(ValidateInfo()){
            // Saving the start tweet
            TwitterMessageController.GetInstance()
                    .SetStartMessage(txtStartTweet.getText());

            // Saving the end tweet
            TwitterMessageController.GetInstance()
                    .SetEndMessage(txtEndTweet.getText());
            
            this.dispose(); // Closing this menu
        }
    }//GEN-LAST:event_btnSetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MessagesUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MessagesUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MessagesUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MessagesUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MessagesUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFileChooser FileChooser;
    private javax.swing.JTable TableTweets;
    private javax.swing.JTextArea TextAreaTweet;
    private javax.swing.JButton btnAddTweet;
    private javax.swing.JButton btnSet;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField txtEndTweet;
    private javax.swing.JTextField txtStartTweet;
    // End of variables declaration//GEN-END:variables
}
