/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.funnybot.main;

import com.funnybot.filecontrollers.FileController;
import com.funnybot.twittercontrollers.TwitterMessageController;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Kamran
 */
public class MessagesUI extends javax.swing.JFrame {

    private int _counter = 0;
    
    /**
     * Creates new form MessagesUI
     */
    public MessagesUI() {
        initComponents();
        
        // Centering the texts in the table
        DefaultTableCellRenderer centerRenderer = 
                new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment( JLabel.CENTER );
        TableTweets.setDefaultRenderer(String.class, centerRenderer);
        TableTweets.setDefaultRenderer(Integer.class, centerRenderer);
        
        LoadMessagesToTable();
    }

    /**
     * This method loads all the tweet messages into the table.
     */
    private void LoadMessagesToTable()
    {
        _counter = 0; // Resetting the counter
        
        // Loop to remove any row data if present
        while(GetTable().getRowCount() != 0)
        {
            // Removing row data
            GetTable().removeRow(0);
        }
        
        // Checking if there is atleast 1 tweet message to show
        if(TwitterMessageController.GetInstance()
                .HasTweetMessage())
        {
            // Getting the message list
            List<String> data = TwitterMessageController.GetInstance()
                    .GetMessages();
            
            // Loop for adding all the tweet messages
            // to the table
            for(int i = 0; i < data.size(); i++)
            {
                // Checking if message isn't end of file
                if(!data.get(i)
                        .equalsIgnoreCase(FileController.CommandDone)){
                    // Adding the tweet message
                    GetTable().addRow(new Object[]{_counter, data.get(i)});
                    _counter++;
                }
            }
        }
    }
    
    /**
     * This method returns the row addable table.
     * 
     * @return The addable table, of type DefaultTableModel
     */
    private DefaultTableModel GetTable(){
        return (DefaultTableModel)TableTweets.getModel();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FileChooser = new javax.swing.JFileChooser();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TextAreaTweet = new javax.swing.JTextArea();
        btnAddTweet = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        TableTweets = new javax.swing.JTable();
        btnLoad = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();

        FileChooser.setSelectedFile(new java.io.File("C:\\Program Files\\NetBeans 8.2\\.txt"));

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setText("Enter Tweet");

        TextAreaTweet.setColumns(20);
        TextAreaTweet.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        TextAreaTweet.setRows(5);
        jScrollPane1.setViewportView(TextAreaTweet);

        btnAddTweet.setText("Add Tweet");
        btnAddTweet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddTweetActionPerformed(evt);
            }
        });

        TableTweets.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Message"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(TableTweets);

        btnLoad.setText("Load Tweets");
        btnLoad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoadActionPerformed(evt);
            }
        });

        btnSave.setText("Save Tweets");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(298, 298, 298)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(312, 312, 312)
                        .addComponent(btnAddTweet))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnLoad)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnSave))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 667, Short.MAX_VALUE)
                            .addComponent(jScrollPane2))))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAddTweet)
                .addGap(56, 56, 56)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLoad)
                    .addComponent(btnSave))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddTweetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddTweetActionPerformed
        TwitterMessageController.GetInstance()
                .AddMessage(TextAreaTweet.getText());
        
        // Adding the tweet message
        GetTable().addRow(new Object[]{_counter, TextAreaTweet.getText()});
        _counter++;
        TextAreaTweet.setText(""); // Removing all texts once added
    }//GEN-LAST:event_btnAddTweetActionPerformed

    private void btnLoadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoadActionPerformed
        // Setting the mode of the file chooser to files only
        FileChooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
        
        int status = FileChooser.showOpenDialog(this); // Getting status of
                                                       // the file chooser
                                                       
        // Condition to check if file chooser selected a file
        if(status == JFileChooser.APPROVE_OPTION)
        {
            FileController.GetInstance().LoadData(FileChooser.getSelectedFile()
                .toPath().toString());
            
            TwitterMessageController.GetInstance()
                    .SetMessages(FileController.GetInstance().GetData());
            
            LoadMessagesToTable();
        }
    }//GEN-LAST:event_btnLoadActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        int status = FileChooser.showSaveDialog(this); // Getting status of
                                                       // the file chooser
                                                       
        // Condition to check if file approved to be saved
        if(status == JFileChooser.APPROVE_OPTION)
        {
            // Saving the data in the selected location with the file name                                                                   
            FileController.GetInstance()
                    .SaveFileOverWrite(FileChooser.getSelectedFile()
                            .toPath().toString(),
                            TwitterMessageController.GetInstance()
                                    .GetMessages());
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MessagesUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MessagesUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MessagesUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MessagesUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MessagesUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFileChooser FileChooser;
    private javax.swing.JTable TableTweets;
    private javax.swing.JTextArea TextAreaTweet;
    private javax.swing.JButton btnAddTweet;
    private javax.swing.JButton btnLoad;
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
